version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: ramalc/helloworld:part2
    deploy:
      #replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "5001:80"
    networks:
      - webnet
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - webnet
  redis:
    image: redis
    ports:
      - "6379:6379"
    # There is an issue trying to moung and map the volume but for now I can live with that issue
    #volumes:
    #  - "/data:/data"
    command: redis-server --appendonly yes
    networks:
      - webnet
networks:
  webnet: